import { ChakraProvider } from "@chakra-ui/react";
import { Inter } from "next/font/google";
import Appbar from "./appbar/Appbar";
import "./global.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Data Pulse",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider>
          <Appbar />
          {children}
        </ChakraProvider>
      </body>
    </html>
  );
}
